---

- hosts: all 
  tasks: 

    - name: "5.4.1 | PATCH | Ensure password creation requirements are configured"
      block:
          - name: "5.4.1 | PATCH | Ensure password creation requirements are configured | Install pam_pwquality module"
            ansible.builtin.package:
                name: libpam-pwquality
                state: present

    - name: "5.4.2 | AUDIT | Ensure lockout for failed password attempts is configured"
      block: 
          - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Check pam faillock is set"
            template:
              src: template.j2
              dest: /etc/pam.d/common-auth
              owner: root
              group: root
              mode: "0644"

          - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Set faillock common-account"
            ansible.builtin.lineinfile:
                path: /etc/pam.d/common-account
                regexp: '^account\s+required\s+pam_faillock.so'
                line: 'account required              pam_faillock.so'

          - name: "5.4.2 | PATCH | Ensure lockout for failed password attempts is configured | Set pam_deny.so and pam_tally.so"
            ansible.builtin.lineinfile:
                path: /etc/security/faillock.conf
                regexp: "{{ item.regexp }}"
                line: "{{ item.line }}"
                insertafter: '^# end of pam-auth-update config'
                create: true
            loop:
                - { regexp: '^deny', line: 'deny = {{ RETRIES }}' }
                - { regexp: '^unlock_time', line: 'unlock_time = {{ UNLOCK_AFTER }}' }
                - { regexp: '^even_deny_root', line: 'even_deny_root' }
                - { regexp: '^audit', line: 'audit' }
                - { regexp: '^root_unlock_time', line: 'root_unlock_time= {{ UNLOCK_AFTER }}' }